name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

        steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${yuhyun00}
        DOCKER_PASSWORD: ${qwer1234}
      run: |
        docker login -u yuhyun00 -p qwer1234
    - name: Build the Docker image
      run: docker build --tag ${yuhyun00}/hangman:latest .
    - name: docker push
      run: docker push ${qwer1234}/hangman:latest


